### ISSUE TITLE
run and nothing

### ISSUE THREAD

**Issue by johnfelipe** [Autodesk-Forge/viewer-nodejs-tutorial#1]
http://200.122.209.134:3003/

![viewerdos](https://cloud.githubusercontent.com/assets/428820/26613858/80457a5a-4582-11e7-8d86-041203ee0e82.png)

What is wrong?

GET http://200.122.209.134:3003/api/token 404 (Not Found)

I create callback with this url 

http://200.122.209.134:3003/api/forge/callback/oauth

**Comment by jaimerosales** [comment]
Did you make sure your Server.js and also the routes/oauth.js are uncommented ? Did you install all the dependencies and ran the server with the correct port, I remember I have it setup for 3000 but I'm sure you probably changed it.

**Comment by johnfelipe** [comment]
/home/felipe/nodejs-forge-viewer-tutorial/server.js:
![server](https://cloud.githubusercontent.com/assets/428820/26644120/528046e6-45f9-11e7-82c7-cbe018a83fff.png)

/home/felipe/nodejs-forge-viewer-tutorial/routes/oauth.js
![routes](https://cloud.githubusercontent.com/assets/428820/26644152/694cbe40-45f9-11e7-9792-b67b464bdbbf.png)

   cp credentials_.js credentials.js

/home/felipe/nodejs-forge-viewer-tutorial/credentials.js:
![credentials](https://cloud.githubusercontent.com/assets/428820/26644198/8dac5d90-45f9-11e7-91ec-9cfa085ae3f8.png)

node_modules:
![nodemodules](https://cloud.githubusercontent.com/assets/428820/26644244/b031b054-45f9-11e7-944d-906884ac918e.png)

**Comment by jaimerosales** [comment]
Did you input the URN in the index.js file correctly ? Can I see that file as well. Everything in the previous ones looked ok.

**Comment by johnfelipe** [comment]
/home/felipe/nodejs-forge-viewer-tutorial/www/js/index.js:
![indexjs](https://cloud.githubusercontent.com/assets/428820/26644716/4a7207bc-45fb-11e7-9595-d64ee21ef9bb.png)

Is possible hangout with your via skype or hangout or something, because only working models.autodesk.io locally:
http://bit.ly/2rEZ6zj

But that only useful for 60 min
Stay alert

**Comment by jaimerosales** [comment]
Ok I have a meeting at the moment that goes until 3:30 EST Time, let's meet at 3:30 my time, where are you based ? 

Cheers,

**Comment by johnfelipe** [comment]
here gmt -5, then ping me in 2 hours
