### ISSUE TITLE
markup3d function issue

### ISSUE THREAD

**Issue by theextremeandy** [Autodesk-Forge/viewer-nodejs-tutorial#14]
HI Jaime,
I try to use your work.
All works ok bat when I use the markup3d function the tooltip "Select new markup... " appears several centimeters at the top of the cursor, compromising the operation.
Can you help me please?
andrea

**Comment by theextremeandy** [comment]
Jaime,
I beautify Viewing.Extension.Markup3D.min.js file
I change the lines that set top and left coordinates of tooltip (at line 13858 approximately)
from this:
top: e.clientY - n.top - 30 + "px",
left: e.clientX - n.left + "px"
to this:
top: e.clientY - n.top - 30,
left: e.clientX - n.left
and now it works!
Thanks
andrea

**Comment by jaimerosales** [comment]
Hey, Thanks a lot for this. if you want to minimize your new version and submit a pull request you are more than welcome. Thanks again for checking this! glad it worked for you.

**Comment by theextremeandy** [comment]
Hi, I created a request, I hope I did exactly the procedure. BR. andrea

**Comment by jaimerosales** [comment]
You did thanks mate! cheers.
