### ISSUE TITLE
Why is everything commented out in server.js, oauth.js, index.js? 

### ISSUE THREAD

**Issue by leefsmp** [Autodesk-Forge/viewer-nodejs-tutorial#2]
all source code is commented out!!

**Comment by jaimerosales** [comment]
Yes, If you go over the Readme you will see why. But I do agree that this should be change. I will work on that to not confuse developers since out of 100% I always get 5-10% of the attendees at a workshop missed the uncomment this section part.

**Comment by jaimerosales** [comment]
Everything now uncommented and changed the workflow of the tutorial.
