### ISSUE TITLE
GET http://IP:3002/api/token 404 (Not Found)

### ISSUE THREAD

**Issue by johnfelipe** [Autodesk-Forge/viewer-nodejs-tutorial#6]
I do this steps:

	git clone https://github.com/Autodesk-Forge/viewer-nodejs-tutorial.git

	cd viewer-nodejs-tutorial/

Put in here `/home/felipe/nodejs-forge-viewer-tutorial/www/js/index.js` URN

	cp credentials_.js credentials.js

Put in here `/home/felipe/nodejs-forge-viewer-tutorial/credentials_.js` my credentials

and `npm start`

![pantallazo-0319](https://user-images.githubusercontent.com/428820/30443957-f7977316-9946-11e7-927b-22bde8492071.png)

And not working, port is open.

Pls review this video https://goo.gl/mT8A8x

Stay alert

**Comment by jaimerosales** [comment]
Hi John,

Still having issues? I update the tutorial to use the most recent Viewer version and a new Server logic to use the Forge NPM for a 2 legged authentication token.

Cheers,
